#include <FS.h>
bool app_poll();
void app_waitAllRelease();
void app_waitAllReleaseConnecting();
void app_waitAllReleaseUnsupported();
void app_sleep(uint32_t, bool);
void settings_save();
void pwr_lcdUndim();
void pwr_sleepCheck();
void pwr_tick(bool);
bool btnSide_hasPressed();
bool btnBig_hasPressed();
bool btnPwr_hasPressed();
bool btnBoth_hasPressed();
bool btnAny_hasPressed();
bool btnSide_isPressed();
bool btnBig_isPressed();
bool btnPwr_isPressed();
bool btnBoth_isPressed();
bool btnAll_isPressed();
void btnSide_clrPressed();
void btnBig_clrPressed();
void btnPwr_clrPressed();
void btnBoth_clrPressed();
void btnAny_clrPressed();
void app_waitAllReleaseGfx(uint8_t);
void app_waitAllRelease();
void app_waitAnyPress(bool);
void app_waitAllReleaseConnecting();
void app_waitAllReleaseUnsupported();
void app_sleep(uint32_t, bool);
int8_t imu_getFocusPull();
int focus_tiltToStepSize(int8_t);
uint32_t shutter_to_millis(uint32_t);
void gui_formatSecondsTime(int32_t, char *, bool);
void gui_formatShutterSpeed(uint32_t, char *);
void gui_formatISO(uint32_t, char *);
int file_readLine(File *, char *, int);
void dissolve_restart(uint16_t);
int32_t get_pinCfgGpio(int32_t);
void safe_all_pins();
