bool app_poll();
void app_waitAllRelease();
void app_waitAllReleaseConnecting();
void app_waitAllReleaseUnsupported();
void app_sleep(uint32_t, bool);
void settings_save();
void pwr_lcdUndim();
void pwr_sleepCheck();
void pwr_tick(bool);
bool btnSide_hasPressed();
bool btnBig_hasPressed();
bool btnPwr_hasPressed();
bool btnBoth_hasPressed();
bool btnAny_hasPressed();
bool btnSide_isPressed();
bool btnBig_isPressed();
bool btnPwr_isPressed();
bool btnBoth_isPressed();
bool btnAll_isPressed();
void btnSide_clrPressed();
void btnBig_clrPressed();
void btnPwr_clrPressed();
void btnBoth_clrPressed();
void btnAny_clrPressed();
void cpufreq_boost();
void infoscr_setup(uint8_t, bool);
void infoscr_print();
void infoscr_printShutterSpeed();
void infoscr_printAperture();
void infoscr_printIso();
void infoscr_printExpoComp();
void infoscr_printExpoMode(uint16_t);
void infoscr_printFocus();
void infoscr_blankLine(bool);
void infoscr_nextPos(bool);
void infoscr_clearRestOfLines();
void infoscr_changeVal(uint8_t, int8_t);
void infoscr_printEditIndicator();
void infoscr_startEdit();

extern uint8_t infoscr_mode;
