#include <alfy_types.h>
bool app_poll();
void app_waitAllRelease();
void app_waitAllReleaseConnecting();
void app_waitAllReleaseUnsupported();
void app_sleep(uint32_t, bool);
void settings_save();
void pwr_lcdUndim();
void pwr_sleepCheck();
void pwr_tick(bool);
bool btnSide_hasPressed();
bool btnBig_hasPressed();
bool btnPwr_hasPressed();
bool btnBoth_hasPressed();
bool btnAny_hasPressed();
bool btnSide_isPressed();
bool btnBig_isPressed();
bool btnPwr_isPressed();
bool btnBoth_isPressed();
bool btnAll_isPressed();
void btnSide_clrPressed();
void btnBig_clrPressed();
void btnPwr_clrPressed();
void btnBoth_clrPressed();
void btnAny_clrPressed();
void wifi_onConnect();
void wifi_onDisconnect(uint8_t, int);
void wifi_init();
void wifi_get_unique_ssid(char *);
void wifiprofile_getIdxFname(uint8_t, char *);
bool wifiprofile_getProfileRaw(uint8_t, char *, char *, uint8_t *, char *);
bool wifiprofile_writeProfileRaw(uint8_t, char *, char *, uint8_t, char *);
bool wifiprofile_getProfile(uint8_t, wifiprofile_t *);
bool wifiprofile_writeProfile(uint8_t, wifiprofile_t *);
bool wifiprofile_connect(uint8_t);
void wifiprofile_deleteAll();
void wifiprofile_deleteProfile(uint8_t);
bool wifiprofile_isBlank(uint8_t);
void wifiprofile_scanFill();
int wifiprofile_autoFind(wifiprofile_t *);
void force_wifi_config(const char *);
void wifi_pswdPromptDrawCb();
int wifi_promptForPassword(char *, char *, char *);
bool wifi_newConnectOrPrompt(uint8_t, wifiprofile_t *, bool, bool);
